---
- import_playbook: docker.yml
- import_playbook: cluster.yml
- import_playbook: portainer.yml
- import_playbook: aws.yml
- import_playbook: ./prometheus/prometheus.yml
- import_playbook: ./elk/elk.yml
